#!/bin/sh

set -e

echo ""
echo " Setting up Gaslight"
echo ""


#
# Check for Bundler
#
if test ! $(which bundle)
then
  echo "  x You need to install Bundler:"
  echo "    gem install bundler"
  exit
else
  echo "  + Bundler found."
fi

#
# Install gems
#
echo "  + Bootstrapping your Rubies."
bundle install --binstubs --local --path vendor --quiet

#
# Setting up .env
#
echo "  + Creating .env"
cp .env.sample .env

#
# Set up the database
#
cp config/database.sample.yml config/database.yml
bundle exec rake db:setup
bundle exec rake db:migrate

echo "Ok, setup complete. Run"
echo "  foreman start"
echo "to start the application."
